baseURL = "https://joelstudler.pages.dev/"
languageCode = "en-us"
title = "Joel Studler"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Joel Studler"
    description = "Drummer, Producer, Mixing Engineer"
    githubUsername = "#"
    accent = "green"
    showBorder = true
    backgroundColor = "ghostwhite"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/jstudler/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/joelstudler/"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/joelstudler/"
    name = "fab fa-linkedin"
    weight = 4

[[menu.icon]]
    url = "https://reelbeetz.bandcamp.com/"
    name = "fab fa-bandcamp"
    weight = 5

[[menu.icon]]
    url = "https://open.spotify.com/artist/5eDvy2hp4fRcg2eWgcrUni?si=US4bR2lcT1WkrKQqxfKK-w"
    name = "fab fa-spotify"
    weight = 6
